#!/bin/bash
# this script can be used to copy new kernel images to the correct place
cd /boot
sudo cp vmlinuz-linux efi/vmlinuz-linux
sudo cp initramfs-linux-fallback.img efi/initramfs-linux-fallback.img
sudo cp initramfs-linux.img efi/initramfs-linux.img
